### PR TITLE
Geometry.sdf

### PR DESCRIPTION
**Pull request by jake163**

### CODE REVIEW

**Comment by ryanmrichard** [comment]
If you could [remove](https://stackoverflow.com/a/15321456) the `Ethane.py` and `Miscellaneous/scf-dictionary` files from this PR I'll go ahead and merge it into master.

**Comment by jake163** [comment]
> 
> 
> If you could [remove](https://stackoverflow.com/a/15321456) the `Ethane.py` and `Miscellaneous/scf-dictionary` files from this PR I'll go ahead and merge it into master.

Coming right up

**Comment by ryanmrichard** [comment]
also please put `.sdf` extensions on the geometry files.

**Comment by jake163** [comment]
> 
> 
> also please put `.sdf` extensions on the geometry files.

Okay.

**Review by ryanmrichard — APPROVED** [review]

**Pull request merged**
