### PR TITLE
Geometries

### PR DESCRIPTION
**Pull request by jake163**

### CODE REVIEW

**Comment by jake163** [comment]
I can't delete the pycache stuff. 

My take is that CO2 is more polarizable (larger monomers, and relatively less polar C=O bonds) than H20 or HF, so it makes sense that we're saving more cycles, comparatively, there. The cycle number similarity between HF and H2O could be from the fact they have similar masses (~20 a.u. vs ~18 a.u. per monomer respectively), and there is hydrogen bonding in both cluster systems.

**Review by ryanmrichard — CHANGES_REQUESTED** [review]
Can we split this PR please? As it stands this PR is a lot to process. Let's start with a PR with just the geometries. After that a PR for the water dimer vs radius. Finally we'll tackle whatever's left (this is where I'm having trouble processing what's going on so this will take some work; I anticipate the other two being more-or-less ready to go).

**Comment by jake163** [comment]
This PR now only has new geometries, pathway changes for old geometries (for better organization), and newly edited versions of older geometries (where the file coordinates are grouped by monomers, instead of by atoms). It still has the pycache stuff unfortunately. 
I can split this PR if you need me to.

**Review by ryanmrichard — CHANGES_REQUESTED** [review]
please remove the `__pycache__` files (I recommend adding `__pycache__/` to the `.gitignore` file so they don't get picked up by git

**Comment by ryanmrichard** [comment]
@jake163 you know you can remove the files from the PR without making another one right?

**Comment by jake163** [comment]
@ryanmrichard It was an accident. Those pycache files had to be deleted from the branch itself and not the PR. I closed this one with the intent of reopening it, but habit forced me to make a new PR.

**Comment by ryanmrichard** [comment]
The branch and the PR are basically the same thing. If you remove the files from the branch you remove them from the PR. The only difference between the branch and the PR are the social coding aspects (like this conversation) which GitHub associates with the PR, but git does not associate with the branch.

**Comment by jake163** [comment]
True. I'm just saying that I had to actually click on the file link before
I could delete, instead of having the option on the PR. I apologize if I'm
not very clear. In any event this wont be a problem in the future.

**Pull request closed without merging**
